# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_verify_symbol <- function(ticker) {
  assert_scalar_character(ticker)
  return(invisible(NULL))
}

assert_return_verify_symbol <- function(value) {
  assert_scalar_logical(value)
  return(value)
}

assert_args_validate_order_params <- function(type, symbol, side, clientOid, price, size, funds, stp, tags, remark, timeInForce, cancelAfter, postOnly, hidden, iceberg, visibleSize) {
  assert_scalar_character(type)
  assert_value_in_set(type, c("limit", "market"))
  assert_scalar_character(symbol)
  assert_scalar_character(side)
  assert_value_in_set(side, c("buy", "sell"))
  if (!is.null(clientOid)) {
    assert_scalar_character(clientOid)
  }
  if (!is.null(price)) {
    assert_any_of(
      price,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(size)) {
    assert_any_of(
      size,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(funds)) {
    assert_any_of(
      funds,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(stp)) {
    assert_scalar_character(stp)
  }
  if (!is.null(tags)) {
    assert_scalar_character(tags)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  if (!is.null(timeInForce)) {
    assert_scalar_character(timeInForce)
  }
  if (!is.null(cancelAfter)) {
    assert_scalar_double(cancelAfter)
  }
  if (!is.null(postOnly)) {
    assert_scalar_logical(postOnly)
  }
  if (!is.null(hidden)) {
    assert_scalar_logical(hidden)
  }
  if (!is.null(iceberg)) {
    assert_scalar_logical(iceberg)
  }
  if (!is.null(visibleSize)) {
    assert_any_of(
      visibleSize,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_validate_order_params <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_validate_margin_order_params <- function(isIsolated, autoBorrow, autoRepay) {
  if (!is.null(isIsolated)) {
    assert_scalar_logical(isIsolated)
  }
  if (!is.null(autoBorrow)) {
    assert_scalar_logical(autoBorrow)
  }
  if (!is.null(autoRepay)) {
    assert_scalar_logical(autoRepay)
  }
  return(invisible(NULL))
}

assert_return_validate_margin_order_params <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_validate_batch_order <- function(order) {
  assert_list(order)
  return(invisible(NULL))
}

assert_return_validate_batch_order <- function(value) {
  assert_list(value)
  return(value)
}

