# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_KucoinDeposit__add_deposit_address <- function(currency, chain, to, amount) {
  assert_scalar_character(currency)
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  if (!is.null(to)) {
    assert_scalar_character(to)
  }
  if (!is.null(amount)) {
    assert_scalar_character(amount)
  }
  return(invisible(NULL))
}

assert_return_KucoinDeposit__add_deposit_address <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinDeposit__get_deposit_addresses <- function(currency, amount, chain) {
  assert_scalar_character(currency)
  if (!is.null(amount)) {
    assert_scalar_character(amount)
  }
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  return(invisible(NULL))
}

assert_return_KucoinDeposit__get_deposit_addresses <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinDeposit__get_deposit_history <- function(currency, status, startAt, endAt, page_size, max_pages) {
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(status)) {
    assert_scalar_character(status)
  }
  if (!is.null(startAt)) {
    assert_scalar_integer(startAt)
  }
  if (!is.null(endAt)) {
    assert_scalar_integer(endAt)
  }
  assert_scalar_count(page_size)
  assert_between(page_size, lower = 1)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_KucoinDeposit__get_deposit_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__get_loan_market <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinLending__get_loan_market <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__get_loan_market_rate <- function(currency) {
  assert_scalar_character(currency)
  return(invisible(NULL))
}

assert_return_KucoinLending__get_loan_market_rate <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__purchase <- function(currency, size, interestRate) {
  assert_scalar_character(currency)
  assert_scalar_double(size)
  assert_scalar_double(interestRate)
  return(invisible(NULL))
}

assert_return_KucoinLending__purchase <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__modify_purchase <- function(currency, purchaseOrderNo, interestRate) {
  assert_scalar_character(currency)
  assert_scalar_character(purchaseOrderNo)
  assert_scalar_double(interestRate)
  return(invisible(NULL))
}

assert_return_KucoinLending__modify_purchase <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__get_purchase_orders <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinLending__get_purchase_orders <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__redeem <- function(currency, size, purchaseOrderNo) {
  assert_scalar_character(currency)
  assert_scalar_double(size)
  assert_scalar_character(purchaseOrderNo)
  return(invisible(NULL))
}

assert_return_KucoinLending__redeem <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__get_redeem_orders <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinLending__get_redeem_orders <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginData__get_cross_margin_symbols <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinMarginData__get_cross_margin_symbols <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinMarginData__get_isolated_margin_symbols <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinMarginData__get_margin_config <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginData__get_collateral_ratio <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinMarginData__get_collateral_ratio <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginData__get_risk_limit <- function(isIsolated, query) {
  assert_scalar_logical(isIsolated)
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinMarginData__get_risk_limit <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinTransfer__add_transfer <- function(clientOid, currency, amount, type, fromAccountType, toAccountType, fromUserId, fromAccountTag, toUserId, toAccountTag) {
  assert_scalar_character(clientOid)
  assert_scalar_character(currency)
  assert_scalar_character(amount)
  assert_scalar_character(type)
  assert_scalar_character(fromAccountType)
  assert_scalar_character(toAccountType)
  if (!is.null(fromUserId)) {
    assert_scalar_character(fromUserId)
  }
  if (!is.null(fromAccountTag)) {
    assert_scalar_character(fromAccountTag)
  }
  if (!is.null(toUserId)) {
    assert_scalar_character(toUserId)
  }
  if (!is.null(toAccountTag)) {
    assert_scalar_character(toAccountTag)
  }
  return(invisible(NULL))
}

assert_return_KucoinTransfer__add_transfer <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinTransfer__get_transferable <- function(currency, type, tag) {
  assert_scalar_character(currency)
  assert_scalar_character(type)
  if (!is.null(tag)) {
    assert_scalar_character(tag)
  }
  return(invisible(NULL))
}

assert_return_KucoinTransfer__get_transferable <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinWithdrawal__add_withdrawal <- function(currency, toAddress, amount, withdrawType, chain, memo, isInner, remark, feeDeductType) {
  assert_scalar_character(currency)
  assert_scalar_character(toAddress)
  assert_scalar_character(amount)
  assert_scalar_character(withdrawType)
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  if (!is.null(memo)) {
    assert_scalar_character(memo)
  }
  if (!is.null(isInner)) {
    assert_scalar_logical(isInner)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  if (!is.null(feeDeductType)) {
    assert_scalar_character(feeDeductType)
  }
  return(invisible(NULL))
}

assert_return_KucoinWithdrawal__add_withdrawal <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinWithdrawal__cancel_withdrawal <- function(withdrawalId) {
  assert_scalar_character(withdrawalId)
  return(invisible(NULL))
}

assert_return_KucoinWithdrawal__cancel_withdrawal <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinWithdrawal__get_withdrawal_quotas <- function(currency, chain) {
  assert_scalar_character(currency)
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  return(invisible(NULL))
}

assert_return_KucoinWithdrawal__get_withdrawal_quotas <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinWithdrawal__get_withdrawal_history <- function(currency, status, startAt, endAt, page_size, max_pages) {
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(status)) {
    assert_scalar_character(status)
  }
  if (!is.null(startAt)) {
    assert_scalar_integer(startAt)
  }
  if (!is.null(endAt)) {
    assert_scalar_integer(endAt)
  }
  assert_scalar_count(page_size)
  assert_between(page_size, lower = 1)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_KucoinWithdrawal__get_withdrawal_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinWithdrawal__get_withdrawal_by_id <- function(withdrawalId) {
  assert_scalar_character(withdrawalId)
  return(invisible(NULL))
}

assert_return_KucoinWithdrawal__get_withdrawal_by_id <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_kucoin_backfill_klines <- function(timeframes, file, base_url, sleep, verbose) {
  assert_character(timeframes)
  assert_no_missing_values(timeframes)
  assert_minimum_length(timeframes, 1L)
  assert_scalar_character(file)
  assert_scalar_character(base_url)
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_logical(verbose)
  return(invisible(NULL))
}

assert_return_kucoin_backfill_klines <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_ms_to_datetime <- function(ms) {
  return(invisible(NULL))
}

assert_return_ms_to_datetime <- function(value) {
  assert_class(value, "POSIXct")
  return(value)
}

assert_args_ns_to_datetime <- function(ns) {
  return(invisible(NULL))
}

assert_return_ns_to_datetime <- function(value) {
  assert_class(value, "POSIXct")
  return(value)
}

assert_args_collapse_string_array_fields <- function(x, fields) {
  assert_list(x)
  assert_character(fields)
  assert_no_missing_values(fields)
  return(invisible(NULL))
}

assert_return_collapse_string_array_fields <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_coerce_cols <- function(dt, cols, fn) {
  assert_class(dt, "data.table")
  assert_character(cols)
  assert_no_missing_values(cols)
  assert_function(fn)
  return(invisible(NULL))
}

assert_return_coerce_cols <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_orderbook <- function(data) {
  assert_list(data)
  return(invisible(NULL))
}

assert_return_parse_orderbook <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("time", "sequence", "side", "level", "price", "size"))
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_character(value[["sequence"]])
  assert_no_missing_values(value[["sequence"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_count(value[["level"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_double(value[["size"]])
  assert_no_missing_values(value[["size"]])
  return(value)
}

assert_args_parse_klines <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_klines <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("datetime", "open", "high", "low", "close", "volume", "turnover"))
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["turnover"]])
  assert_no_missing_values(value[["turnover"]])
  return(value)
}

assert_args_flatten_pages <- function(pages) {
  assert_list(pages)
  return(invisible(NULL))
}

assert_return_flatten_pages <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_sign_request <- function(req, keys, method, path, body, .get_timestamp_ms) {
  assert_class(req, "httr2_request")
  assert_list(keys)
  assert_scalar_character(method)
  assert_scalar_character(path)
  assert_scalar_character(body)
  if (!is.null(.get_timestamp_ms)) {
    assert_function(.get_timestamp_ms)
  }
  return(invisible(NULL))
}

assert_return_sign_request <- function(value) {
  assert_class(value, "httr2_request")
  return(value)
}

assert_args_kucoin_serialize_body <- function(body) {
  if (!is.null(body)) {
    assert_list(body)
  }
  return(invisible(NULL))
}

assert_return_kucoin_serialize_body <- function(value) {
  if (!is.null(value)) {
    assert_scalar_character(value)
  }
  return(value)
}

assert_args_kucoin_sign_req <- function(req, keys, ctx) {
  assert_class(req, "httr2_request")
  assert_list(keys)
  assert_list(ctx)
  return(invisible(NULL))
}

assert_return_kucoin_sign_req <- function(value) {
  assert_class(value, "httr2_request")
  return(value)
}

assert_args_parse_kucoin_response <- function(resp) {
  assert_class(resp, "httr2_response")
  return(invisible(NULL))
}

assert_return_parse_kucoin_response <- function(value) {
  return(value)
}

assert_args_kucoin_paginate <- function(base_url, endpoint, method, query, body, keys, sign, parse_envelope, .perform, .parser, is_async, page_size, max_pages, items_field, timeout, .get_timestamp_ms) {
  assert_scalar_character(base_url)
  assert_scalar_character(endpoint)
  assert_scalar_character(method)
  assert_list(query)
  if (!is.null(body)) {
    assert_list(body)
  }
  if (!is.null(keys)) {
    assert_list(keys)
  }
  if (!is.null(sign)) {
    assert_function(sign)
  }
  assert_function(parse_envelope)
  assert_function(.perform)
  assert_function(.parser)
  assert_scalar_logical(is_async)
  assert_scalar_count(page_size)
  assert_between(page_size, lower = 1)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  assert_scalar_character(items_field)
  assert_scalar_double(timeout)
  assert_between(timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  if (!is.null(.get_timestamp_ms)) {
    assert_function(.get_timestamp_ms)
  }
  return(invisible(NULL))
}

assert_return_kucoin_paginate <- function(value) {
  return(value)
}

assert_args_verify_symbol <- function(ticker) {
  assert_scalar_character(ticker)
  return(invisible(NULL))
}

assert_return_verify_symbol <- function(value) {
  assert_scalar_logical(value)
  return(value)
}

assert_args_validate_order_params <- function(type, symbol, side, clientOid, price, size, funds, stp, tags, remark, timeInForce, cancelAfter, postOnly, hidden, iceberg, visibleSize) {
  assert_scalar_character(type)
  assert_value_in_set(type, c("limit", "market"))
  assert_scalar_character(symbol)
  assert_scalar_character(side)
  assert_value_in_set(side, c("buy", "sell"))
  if (!is.null(clientOid)) {
    assert_scalar_character(clientOid)
  }
  if (!is.null(price)) {
    assert_any_of(
      price,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(size)) {
    assert_any_of(
      size,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(funds)) {
    assert_any_of(
      funds,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(stp)) {
    assert_scalar_character(stp)
  }
  if (!is.null(tags)) {
    assert_scalar_character(tags)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  if (!is.null(timeInForce)) {
    assert_scalar_character(timeInForce)
  }
  if (!is.null(cancelAfter)) {
    assert_scalar_double(cancelAfter)
  }
  if (!is.null(postOnly)) {
    assert_scalar_logical(postOnly)
  }
  if (!is.null(hidden)) {
    assert_scalar_logical(hidden)
  }
  if (!is.null(iceberg)) {
    assert_scalar_logical(iceberg)
  }
  if (!is.null(visibleSize)) {
    assert_any_of(
      visibleSize,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_validate_order_params <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_validate_margin_order_params <- function(isIsolated, autoBorrow, autoRepay) {
  if (!is.null(isIsolated)) {
    assert_scalar_logical(isIsolated)
  }
  if (!is.null(autoBorrow)) {
    assert_scalar_logical(autoBorrow)
  }
  if (!is.null(autoRepay)) {
    assert_scalar_logical(autoRepay)
  }
  return(invisible(NULL))
}

assert_return_validate_margin_order_params <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_validate_batch_order <- function(order) {
  assert_list(order)
  return(invisible(NULL))
}

assert_return_validate_batch_order <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_get_base_url <- function(url) {
  if (!is.null(url)) {
    assert_scalar_character(url)
  }
  return(invisible(NULL))
}

assert_return_get_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_get_futures_base_url <- function(url) {
  if (!is.null(url)) {
    assert_scalar_character(url)
  }
  return(invisible(NULL))
}

assert_return_get_futures_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_get_api_keys <- function(api_key, api_secret, api_passphrase, key_version) {
  assert_scalar_character(api_key)
  assert_scalar_character(api_secret)
  assert_scalar_character(api_passphrase)
  assert_scalar_character(key_version)
  return(invisible(NULL))
}

assert_return_get_api_keys <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_get_sub_account <- function(sub_account_name, sub_account_password) {
  assert_scalar_character(sub_account_name)
  assert_scalar_character(sub_account_password)
  return(invisible(NULL))
}

assert_return_get_sub_account <- function(value) {
  assert_list(value)
  return(value)
}

assert_return_time_convert_from_kucoin <- function(value) {
  assert_class(value, "POSIXct")
  return(value)
}

assert_return_time_convert_to_kucoin <- function(value) {
  assert_any_of(
    value,
    function(.x) {
      assert_scalar_double(.x)
    },
    function(.x) {
      assert_scalar_integer(.x)
    }
  )
  return(value)
}

