# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_return_KucoinAccount__get_summary <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinAccount__get_apikey_info <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinAccount__get_spot_account_type <- function(value) {
  assert_scalar_logical(value)
  return(value)
}

assert_args_KucoinAccount__get_spot_accounts <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinAccount__get_spot_accounts <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinAccount__get_spot_account_detail <- function(accountId) {
  assert_scalar_character(accountId)
  return(invisible(NULL))
}

assert_return_KucoinAccount__get_spot_account_detail <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinAccount__get_cross_margin_account <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinAccount__get_cross_margin_account <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinAccount__get_isolated_margin_account <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinAccount__get_isolated_margin_account <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinAccount__get_spot_ledger <- function(query, page_size, max_pages) {
  assert_list(query)
  assert_scalar_count(page_size)
  assert_between(page_size, lower = 1)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_KucoinAccount__get_spot_ledger <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinAccount__get_hf_ledger <- function(currency, direction, bizType, lastId, limit, startAt, endAt) {
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(direction)) {
    assert_scalar_character(direction)
  }
  if (!is.null(bizType)) {
    assert_scalar_character(bizType)
  }
  if (!is.null(lastId)) {
    assert_scalar_character(lastId)
  }
  if (!is.null(limit)) {
    assert_scalar_integer(limit)
  }
  if (!is.null(startAt)) {
    assert_scalar_integer(startAt)
  }
  if (!is.null(endAt)) {
    assert_scalar_integer(endAt)
  }
  return(invisible(NULL))
}

assert_return_KucoinAccount__get_hf_ledger <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinAccount__get_base_fee_rate <- function(currencyType) {
  if (!is.null(currencyType)) {
    assert_scalar_integer(currencyType)
  }
  return(invisible(NULL))
}

assert_return_KucoinAccount__get_base_fee_rate <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinAccount__get_fee_rate <- function(symbols) {
  assert_scalar_character(symbols)
  return(invisible(NULL))
}

assert_return_KucoinAccount__get_fee_rate <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinDeposit__add_deposit_address <- function(currency, chain, to, amount) {
  assert_scalar_character(currency)
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  if (!is.null(to)) {
    assert_scalar_character(to)
  }
  if (!is.null(amount)) {
    assert_scalar_character(amount)
  }
  return(invisible(NULL))
}

assert_return_KucoinDeposit__add_deposit_address <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinDeposit__get_deposit_addresses <- function(currency, amount, chain) {
  assert_scalar_character(currency)
  if (!is.null(amount)) {
    assert_scalar_character(amount)
  }
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  return(invisible(NULL))
}

assert_return_KucoinDeposit__get_deposit_addresses <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinDeposit__get_deposit_history <- function(currency, status, startAt, endAt, page_size, max_pages) {
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(status)) {
    assert_scalar_character(status)
  }
  if (!is.null(startAt)) {
    assert_scalar_integer(startAt)
  }
  if (!is.null(endAt)) {
    assert_scalar_integer(endAt)
  }
  assert_scalar_count(page_size)
  assert_between(page_size, lower = 1)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_KucoinDeposit__get_deposit_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__initialize <- function(keys, base_url, async) {
  assert_list(keys)
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__initialize <- function(value) {
  assert_class(value, "KucoinFuturesAccount")
  return(value)
}

assert_args_KucoinFuturesAccount__get_account_overview <- function(currency) {
  assert_scalar_character(currency)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__get_account_overview <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__get_position <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__get_position <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__get_positions <- function(currency) {
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__get_positions <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__get_positions_history <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__get_positions_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__get_margin_mode <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__get_margin_mode <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__set_margin_mode <- function(symbol, marginMode) {
  assert_scalar_character(symbol)
  assert_scalar_character(marginMode)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__set_margin_mode <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__get_cross_margin_leverage <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__get_cross_margin_leverage <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__set_cross_margin_leverage <- function(symbol, leverage) {
  assert_scalar_character(symbol)
  assert_scalar_count(leverage)
  assert_between(leverage, lower = 1)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__set_cross_margin_leverage <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__get_max_open_size <- function(symbol, price, leverage) {
  assert_scalar_character(symbol)
  assert_scalar_character(price)
  assert_scalar_count(leverage)
  assert_between(leverage, lower = 1)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__get_max_open_size <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__get_max_withdraw_margin <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__get_max_withdraw_margin <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__add_isolated_margin <- function(symbol, margin, bizNo) {
  assert_scalar_character(symbol)
  assert_scalar_double(margin)
  assert_scalar_character(bizNo)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__add_isolated_margin <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__remove_isolated_margin <- function(symbol, withdrawAmount) {
  assert_scalar_character(symbol)
  assert_scalar_double(withdrawAmount)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__remove_isolated_margin <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__get_risk_limit <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__get_risk_limit <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesAccount__get_funding_history <- function(symbol, query) {
  assert_scalar_character(symbol)
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinFuturesAccount__get_funding_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesMarketData__initialize <- function(keys, base_url, async) {
  assert_list(keys)
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_KucoinFuturesMarketData__initialize <- function(value) {
  assert_class(value, "KucoinFuturesMarketData")
  return(value)
}

assert_args_KucoinFuturesMarketData__get_contract <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesMarketData__get_contract <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinFuturesMarketData__get_all_contracts <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesMarketData__get_ticker <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesMarketData__get_ticker <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinFuturesMarketData__get_all_tickers <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesMarketData__get_part_orderbook <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesMarketData__get_part_orderbook <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesMarketData__get_full_orderbook <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesMarketData__get_full_orderbook <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesMarketData__get_trade_history <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesMarketData__get_trade_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesMarketData__get_klines <- function(symbol, granularity, fetch_all, sleep) {
  assert_scalar_character(symbol)
  assert_scalar_count(granularity)
  assert_between(granularity, lower = 1)
  assert_scalar_logical(fetch_all)
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_KucoinFuturesMarketData__get_klines <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("datetime", "open", "high", "low", "close", "volume", "turnover"))
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["turnover"]])
  assert_no_missing_values(value[["turnover"]])
  return(value)
}

assert_args_KucoinFuturesMarketData__get_mark_price <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesMarketData__get_mark_price <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesMarketData__get_funding_rate <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesMarketData__get_funding_rate <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinFuturesMarketData__get_funding_history <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinFuturesMarketData__get_funding_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinFuturesMarketData__get_server_time <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinFuturesMarketData__get_service_status <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_parse_futures_orderbook <- function(data) {
  assert_list(data)
  return(invisible(NULL))
}

assert_return_parse_futures_orderbook <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_futures_klines <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_futures_klines <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("datetime", "open", "high", "low", "close", "volume", "turnover"))
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["turnover"]])
  assert_no_missing_values(value[["turnover"]])
  return(value)
}

assert_args_KucoinLending__get_loan_market <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinLending__get_loan_market <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__get_loan_market_rate <- function(currency) {
  assert_scalar_character(currency)
  return(invisible(NULL))
}

assert_return_KucoinLending__get_loan_market_rate <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__purchase <- function(currency, size, interestRate) {
  assert_scalar_character(currency)
  assert_scalar_double(size)
  assert_scalar_double(interestRate)
  return(invisible(NULL))
}

assert_return_KucoinLending__purchase <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__modify_purchase <- function(currency, purchaseOrderNo, interestRate) {
  assert_scalar_character(currency)
  assert_scalar_character(purchaseOrderNo)
  assert_scalar_double(interestRate)
  return(invisible(NULL))
}

assert_return_KucoinLending__modify_purchase <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__get_purchase_orders <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinLending__get_purchase_orders <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__redeem <- function(currency, size, purchaseOrderNo) {
  assert_scalar_character(currency)
  assert_scalar_double(size)
  assert_scalar_character(purchaseOrderNo)
  return(invisible(NULL))
}

assert_return_KucoinLending__redeem <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinLending__get_redeem_orders <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinLending__get_redeem_orders <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginData__get_cross_margin_symbols <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinMarginData__get_cross_margin_symbols <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinMarginData__get_isolated_margin_symbols <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinMarginData__get_margin_config <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginData__get_collateral_ratio <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinMarginData__get_collateral_ratio <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginData__get_risk_limit <- function(isIsolated, query) {
  assert_scalar_logical(isIsolated)
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinMarginData__get_risk_limit <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginTrading__open_short <- function(symbol, size, funds, type, price, isIsolated, clientOid, stp, remark, timeInForce, cancelAfter, postOnly, hidden, iceberg, visibleSize, dry_run) {
  assert_scalar_character(symbol)
  if (!is.null(size)) {
    assert_scalar_double(size)
  }
  if (!is.null(funds)) {
    assert_scalar_double(funds)
  }
  assert_scalar_character(type)
  if (!is.null(price)) {
    assert_scalar_double(price)
  }
  assert_scalar_logical(isIsolated)
  if (!is.null(clientOid)) {
    assert_scalar_character(clientOid)
  }
  if (!is.null(stp)) {
    assert_scalar_character(stp)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  if (!is.null(timeInForce)) {
    assert_scalar_character(timeInForce)
  }
  if (!is.null(cancelAfter)) {
    assert_scalar_double(cancelAfter)
  }
  if (!is.null(postOnly)) {
    assert_scalar_logical(postOnly)
  }
  if (!is.null(hidden)) {
    assert_scalar_logical(hidden)
  }
  if (!is.null(iceberg)) {
    assert_scalar_logical(iceberg)
  }
  if (!is.null(visibleSize)) {
    assert_scalar_double(visibleSize)
  }
  assert_scalar_logical(dry_run)
  return(invisible(NULL))
}

assert_return_KucoinMarginTrading__open_short <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginTrading__close_short <- function(symbol, size, funds, type, price, isIsolated, clientOid, stp, remark, timeInForce, cancelAfter, postOnly, hidden, iceberg, visibleSize, dry_run) {
  assert_scalar_character(symbol)
  if (!is.null(size)) {
    assert_scalar_double(size)
  }
  if (!is.null(funds)) {
    assert_scalar_double(funds)
  }
  assert_scalar_character(type)
  if (!is.null(price)) {
    assert_scalar_double(price)
  }
  assert_scalar_logical(isIsolated)
  if (!is.null(clientOid)) {
    assert_scalar_character(clientOid)
  }
  if (!is.null(stp)) {
    assert_scalar_character(stp)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  if (!is.null(timeInForce)) {
    assert_scalar_character(timeInForce)
  }
  if (!is.null(cancelAfter)) {
    assert_scalar_double(cancelAfter)
  }
  if (!is.null(postOnly)) {
    assert_scalar_logical(postOnly)
  }
  if (!is.null(hidden)) {
    assert_scalar_logical(hidden)
  }
  if (!is.null(iceberg)) {
    assert_scalar_logical(iceberg)
  }
  if (!is.null(visibleSize)) {
    assert_scalar_double(visibleSize)
  }
  assert_scalar_logical(dry_run)
  return(invisible(NULL))
}

assert_return_KucoinMarginTrading__close_short <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginTrading__open_long <- function(symbol, size, funds, type, price, isIsolated, clientOid, stp, remark, timeInForce, cancelAfter, postOnly, hidden, iceberg, visibleSize, dry_run) {
  assert_scalar_character(symbol)
  if (!is.null(size)) {
    assert_scalar_double(size)
  }
  if (!is.null(funds)) {
    assert_scalar_double(funds)
  }
  assert_scalar_character(type)
  if (!is.null(price)) {
    assert_scalar_double(price)
  }
  assert_scalar_logical(isIsolated)
  if (!is.null(clientOid)) {
    assert_scalar_character(clientOid)
  }
  if (!is.null(stp)) {
    assert_scalar_character(stp)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  if (!is.null(timeInForce)) {
    assert_scalar_character(timeInForce)
  }
  if (!is.null(cancelAfter)) {
    assert_scalar_double(cancelAfter)
  }
  if (!is.null(postOnly)) {
    assert_scalar_logical(postOnly)
  }
  if (!is.null(hidden)) {
    assert_scalar_logical(hidden)
  }
  if (!is.null(iceberg)) {
    assert_scalar_logical(iceberg)
  }
  if (!is.null(visibleSize)) {
    assert_scalar_double(visibleSize)
  }
  assert_scalar_logical(dry_run)
  return(invisible(NULL))
}

assert_return_KucoinMarginTrading__open_long <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginTrading__close_long <- function(symbol, size, funds, type, price, isIsolated, clientOid, stp, remark, timeInForce, cancelAfter, postOnly, hidden, iceberg, visibleSize, dry_run) {
  assert_scalar_character(symbol)
  if (!is.null(size)) {
    assert_scalar_double(size)
  }
  if (!is.null(funds)) {
    assert_scalar_double(funds)
  }
  assert_scalar_character(type)
  if (!is.null(price)) {
    assert_scalar_double(price)
  }
  assert_scalar_logical(isIsolated)
  if (!is.null(clientOid)) {
    assert_scalar_character(clientOid)
  }
  if (!is.null(stp)) {
    assert_scalar_character(stp)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  if (!is.null(timeInForce)) {
    assert_scalar_character(timeInForce)
  }
  if (!is.null(cancelAfter)) {
    assert_scalar_double(cancelAfter)
  }
  if (!is.null(postOnly)) {
    assert_scalar_logical(postOnly)
  }
  if (!is.null(hidden)) {
    assert_scalar_logical(hidden)
  }
  if (!is.null(iceberg)) {
    assert_scalar_logical(iceberg)
  }
  if (!is.null(visibleSize)) {
    assert_scalar_double(visibleSize)
  }
  assert_scalar_logical(dry_run)
  return(invisible(NULL))
}

assert_return_KucoinMarginTrading__close_long <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginTrading__borrow <- function(currency, size, timeInForce, isIsolated, symbol, isHf) {
  assert_scalar_character(currency)
  assert_scalar_double(size)
  assert_scalar_character(timeInForce)
  assert_scalar_logical(isIsolated)
  if (!is.null(symbol)) {
    assert_scalar_character(symbol)
  }
  assert_scalar_logical(isHf)
  return(invisible(NULL))
}

assert_return_KucoinMarginTrading__borrow <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginTrading__repay <- function(currency, size) {
  assert_scalar_character(currency)
  assert_scalar_double(size)
  return(invisible(NULL))
}

assert_return_KucoinMarginTrading__repay <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginTrading__get_borrow_history <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinMarginTrading__get_borrow_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginTrading__get_repay_history <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinMarginTrading__get_repay_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginTrading__get_interest_history <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinMarginTrading__get_interest_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarginTrading__get_borrow_rate <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinMarginTrading__get_borrow_rate <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinMarginTrading__modify_leverage <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarketData__get_announcements <- function(query, page_size, max_pages) {
  assert_list(query)
  assert_scalar_count(page_size)
  assert_between(page_size, lower = 1)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_announcements <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarketData__get_currency <- function(currency, chain) {
  assert_scalar_character(currency)
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_currency <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinMarketData__get_all_currencies <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarketData__get_symbol <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_symbol <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarketData__get_all_symbols <- function(market) {
  if (!is.null(market)) {
    assert_scalar_character(market)
  }
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_all_symbols <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarketData__get_ticker <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_ticker <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinMarketData__get_all_tickers <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarketData__get_trade_history <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_trade_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarketData__get_part_orderbook <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_part_orderbook <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("time", "sequence", "side", "level", "price", "size"))
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_character(value[["sequence"]])
  assert_no_missing_values(value[["sequence"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_count(value[["level"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_double(value[["size"]])
  assert_no_missing_values(value[["size"]])
  return(value)
}

assert_args_KucoinMarketData__get_full_orderbook <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_full_orderbook <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("time", "sequence", "side", "level", "price", "size"))
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_character(value[["sequence"]])
  assert_no_missing_values(value[["sequence"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_count(value[["level"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_double(value[["size"]])
  assert_no_missing_values(value[["size"]])
  return(value)
}

assert_args_KucoinMarketData__get_24hr_stats <- function(symbol) {
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_24hr_stats <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinMarketData__get_market_list <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarketData__get_klines <- function(symbol, timeframe) {
  assert_scalar_character(symbol)
  assert_scalar_character(timeframe)
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_klines <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("datetime", "open", "high", "low", "close", "volume", "turnover"))
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["turnover"]])
  assert_no_missing_values(value[["turnover"]])
  return(value)
}

assert_return_KucoinMarketData__get_server_time <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_KucoinMarketData__get_service_status <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinMarketData__get_fiat_prices <- function(base, currencies) {
  if (!is.null(base)) {
    assert_scalar_character(base)
  }
  if (!is.null(currencies)) {
    assert_scalar_character(currencies)
  }
  return(invisible(NULL))
}

assert_return_KucoinMarketData__get_fiat_prices <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinOcoOrders__add_order <- function(symbol, side, price, size, stopPrice, limitPrice, clientOid, remark, tradeType) {
  assert_scalar_character(symbol)
  assert_scalar_character(side)
  assert_any_of(
    price,
    function(.x) {
      assert_scalar_double(.x)
    },
    function(.x) {
      assert_scalar_character(.x)
    }
  )
  assert_any_of(
    size,
    function(.x) {
      assert_scalar_double(.x)
    },
    function(.x) {
      assert_scalar_character(.x)
    }
  )
  assert_any_of(
    stopPrice,
    function(.x) {
      assert_scalar_double(.x)
    },
    function(.x) {
      assert_scalar_character(.x)
    }
  )
  assert_any_of(
    limitPrice,
    function(.x) {
      assert_scalar_double(.x)
    },
    function(.x) {
      assert_scalar_character(.x)
    }
  )
  if (!is.null(clientOid)) {
    assert_scalar_character(clientOid)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  assert_scalar_character(tradeType)
  return(invisible(NULL))
}

assert_return_KucoinOcoOrders__add_order <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinOcoOrders__cancel_order_by_id <- function(orderId) {
  assert_scalar_character(orderId)
  return(invisible(NULL))
}

assert_return_KucoinOcoOrders__cancel_order_by_id <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinOcoOrders__cancel_order_by_client_oid <- function(clientOid) {
  assert_scalar_character(clientOid)
  return(invisible(NULL))
}

assert_return_KucoinOcoOrders__cancel_order_by_client_oid <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinOcoOrders__cancel_all <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinOcoOrders__cancel_all <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinOcoOrders__get_order_by_id <- function(orderId) {
  assert_scalar_character(orderId)
  return(invisible(NULL))
}

assert_return_KucoinOcoOrders__get_order_by_id <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinOcoOrders__get_order_by_client_oid <- function(clientOid) {
  assert_scalar_character(clientOid)
  return(invisible(NULL))
}

assert_return_KucoinOcoOrders__get_order_by_client_oid <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinOcoOrders__get_order_detail_by_id <- function(orderId) {
  assert_scalar_character(orderId)
  return(invisible(NULL))
}

assert_return_KucoinOcoOrders__get_order_detail_by_id <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinOcoOrders__get_order_list <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinOcoOrders__get_order_list <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinStopOrders__add_order <- function(type, symbol, side, stopPrice, clientOid, price, size, funds, stp, remark, timeInForce, cancelAfter, postOnly, hidden, iceberg, visibleSize, tradeType) {
  assert_scalar_character(type)
  assert_scalar_character(symbol)
  assert_scalar_character(side)
  assert_any_of(
    stopPrice,
    function(.x) {
      assert_scalar_double(.x)
    },
    function(.x) {
      assert_scalar_character(.x)
    }
  )
  if (!is.null(clientOid)) {
    assert_scalar_character(clientOid)
  }
  if (!is.null(price)) {
    assert_any_of(
      price,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(size)) {
    assert_any_of(
      size,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(funds)) {
    assert_any_of(
      funds,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(stp)) {
    assert_scalar_character(stp)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  if (!is.null(timeInForce)) {
    assert_scalar_character(timeInForce)
  }
  if (!is.null(cancelAfter)) {
    assert_scalar_double(cancelAfter)
  }
  if (!is.null(postOnly)) {
    assert_scalar_logical(postOnly)
  }
  if (!is.null(hidden)) {
    assert_scalar_logical(hidden)
  }
  if (!is.null(iceberg)) {
    assert_scalar_logical(iceberg)
  }
  if (!is.null(visibleSize)) {
    assert_any_of(
      visibleSize,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  assert_scalar_character(tradeType)
  return(invisible(NULL))
}

assert_return_KucoinStopOrders__add_order <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinStopOrders__cancel_order_by_id <- function(orderId) {
  assert_scalar_character(orderId)
  return(invisible(NULL))
}

assert_return_KucoinStopOrders__cancel_order_by_id <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinStopOrders__cancel_order_by_client_oid <- function(clientOid, symbol) {
  assert_scalar_character(clientOid)
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinStopOrders__cancel_order_by_client_oid <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinStopOrders__cancel_all <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinStopOrders__cancel_all <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinStopOrders__get_order_by_id <- function(orderId) {
  assert_scalar_character(orderId)
  return(invisible(NULL))
}

assert_return_KucoinStopOrders__get_order_by_id <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinStopOrders__get_order_by_client_oid <- function(clientOid, symbol) {
  assert_scalar_character(clientOid)
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_KucoinStopOrders__get_order_by_client_oid <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinStopOrders__get_order_list <- function(query) {
  assert_list(query)
  return(invisible(NULL))
}

assert_return_KucoinStopOrders__get_order_list <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinSubAccount__add_sub_account <- function(password, subName, access, remarks) {
  assert_scalar_character(password)
  assert_scalar_character(subName)
  assert_scalar_character(access)
  if (!is.null(remarks)) {
    assert_scalar_character(remarks)
  }
  return(invisible(NULL))
}

assert_return_KucoinSubAccount__add_sub_account <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinSubAccount__get_sub_account_list <- function(page_size, max_pages) {
  assert_scalar_count(page_size)
  assert_between(page_size, lower = 1)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_KucoinSubAccount__get_sub_account_list <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinSubAccount__get_detail_balance <- function(subUserId, includeBaseAmount) {
  assert_scalar_character(subUserId)
  assert_scalar_logical(includeBaseAmount)
  return(invisible(NULL))
}

assert_return_KucoinSubAccount__get_detail_balance <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinSubAccount__get_all_spot_balances <- function(page_size, max_pages) {
  assert_scalar_count(page_size)
  assert_between(page_size, lower = 1)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_KucoinSubAccount__get_all_spot_balances <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinTransfer__add_transfer <- function(clientOid, currency, amount, type, fromAccountType, toAccountType, fromUserId, fromAccountTag, toUserId, toAccountTag) {
  assert_scalar_character(clientOid)
  assert_scalar_character(currency)
  assert_scalar_character(amount)
  assert_scalar_character(type)
  assert_scalar_character(fromAccountType)
  assert_scalar_character(toAccountType)
  if (!is.null(fromUserId)) {
    assert_scalar_character(fromUserId)
  }
  if (!is.null(fromAccountTag)) {
    assert_scalar_character(fromAccountTag)
  }
  if (!is.null(toUserId)) {
    assert_scalar_character(toUserId)
  }
  if (!is.null(toAccountTag)) {
    assert_scalar_character(toAccountTag)
  }
  return(invisible(NULL))
}

assert_return_KucoinTransfer__add_transfer <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinTransfer__get_transferable <- function(currency, type, tag) {
  assert_scalar_character(currency)
  assert_scalar_character(type)
  if (!is.null(tag)) {
    assert_scalar_character(tag)
  }
  return(invisible(NULL))
}

assert_return_KucoinTransfer__get_transferable <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinWithdrawal__add_withdrawal <- function(currency, toAddress, amount, withdrawType, chain, memo, isInner, remark, feeDeductType) {
  assert_scalar_character(currency)
  assert_scalar_character(toAddress)
  assert_scalar_character(amount)
  assert_scalar_character(withdrawType)
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  if (!is.null(memo)) {
    assert_scalar_character(memo)
  }
  if (!is.null(isInner)) {
    assert_scalar_logical(isInner)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  if (!is.null(feeDeductType)) {
    assert_scalar_character(feeDeductType)
  }
  return(invisible(NULL))
}

assert_return_KucoinWithdrawal__add_withdrawal <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinWithdrawal__cancel_withdrawal <- function(withdrawalId) {
  assert_scalar_character(withdrawalId)
  return(invisible(NULL))
}

assert_return_KucoinWithdrawal__cancel_withdrawal <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinWithdrawal__get_withdrawal_quotas <- function(currency, chain) {
  assert_scalar_character(currency)
  if (!is.null(chain)) {
    assert_scalar_character(chain)
  }
  return(invisible(NULL))
}

assert_return_KucoinWithdrawal__get_withdrawal_quotas <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinWithdrawal__get_withdrawal_history <- function(currency, status, startAt, endAt, page_size, max_pages) {
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(status)) {
    assert_scalar_character(status)
  }
  if (!is.null(startAt)) {
    assert_scalar_integer(startAt)
  }
  if (!is.null(endAt)) {
    assert_scalar_integer(endAt)
  }
  assert_scalar_count(page_size)
  assert_between(page_size, lower = 1)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  return(invisible(NULL))
}

assert_return_KucoinWithdrawal__get_withdrawal_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_KucoinWithdrawal__get_withdrawal_by_id <- function(withdrawalId) {
  assert_scalar_character(withdrawalId)
  return(invisible(NULL))
}

assert_return_KucoinWithdrawal__get_withdrawal_by_id <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_kucoin_backfill_klines <- function(timeframes, file, base_url, sleep, verbose) {
  assert_character(timeframes)
  assert_no_missing_values(timeframes)
  assert_minimum_length(timeframes, 1L)
  assert_scalar_character(file)
  assert_scalar_character(base_url)
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_logical(verbose)
  return(invisible(NULL))
}

assert_return_kucoin_backfill_klines <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_ms_to_datetime <- function(ms) {
  return(invisible(NULL))
}

assert_return_ms_to_datetime <- function(value) {
  assert_class(value, "POSIXct")
  return(value)
}

assert_args_ns_to_datetime <- function(ns) {
  return(invisible(NULL))
}

assert_return_ns_to_datetime <- function(value) {
  assert_class(value, "POSIXct")
  return(value)
}

assert_args_collapse_string_array_fields <- function(x, fields) {
  assert_list(x)
  assert_character(fields)
  assert_no_missing_values(fields)
  return(invisible(NULL))
}

assert_return_collapse_string_array_fields <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_coerce_cols <- function(dt, cols, fn) {
  assert_class(dt, "data.table")
  assert_character(cols)
  assert_no_missing_values(cols)
  assert_function(fn)
  return(invisible(NULL))
}

assert_return_coerce_cols <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_orderbook <- function(data) {
  assert_list(data)
  return(invisible(NULL))
}

assert_return_parse_orderbook <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("time", "sequence", "side", "level", "price", "size"))
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_character(value[["sequence"]])
  assert_no_missing_values(value[["sequence"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_count(value[["level"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_double(value[["size"]])
  assert_no_missing_values(value[["size"]])
  return(value)
}

assert_args_parse_klines <- function(data) {
  if (!is.null(data)) {
    assert_list(data)
  }
  return(invisible(NULL))
}

assert_return_parse_klines <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("datetime", "open", "high", "low", "close", "volume", "turnover"))
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["turnover"]])
  assert_no_missing_values(value[["turnover"]])
  return(value)
}

assert_args_flatten_pages <- function(pages) {
  assert_list(pages)
  return(invisible(NULL))
}

assert_return_flatten_pages <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_sign_request <- function(req, keys, method, path, body, .get_timestamp_ms) {
  assert_class(req, "httr2_request")
  assert_list(keys)
  assert_scalar_character(method)
  assert_scalar_character(path)
  assert_scalar_character(body)
  if (!is.null(.get_timestamp_ms)) {
    assert_function(.get_timestamp_ms)
  }
  return(invisible(NULL))
}

assert_return_sign_request <- function(value) {
  assert_class(value, "httr2_request")
  return(value)
}

assert_args_kucoin_serialize_body <- function(body) {
  if (!is.null(body)) {
    assert_list(body)
  }
  return(invisible(NULL))
}

assert_return_kucoin_serialize_body <- function(value) {
  if (!is.null(value)) {
    assert_scalar_character(value)
  }
  return(value)
}

assert_args_kucoin_sign_req <- function(req, keys, ctx) {
  assert_class(req, "httr2_request")
  assert_list(keys)
  assert_list(ctx)
  return(invisible(NULL))
}

assert_return_kucoin_sign_req <- function(value) {
  assert_class(value, "httr2_request")
  return(value)
}

assert_args_parse_kucoin_response <- function(resp) {
  assert_class(resp, "httr2_response")
  return(invisible(NULL))
}

assert_return_parse_kucoin_response <- function(value) {
  return(value)
}

assert_args_kucoin_paginate <- function(base_url, endpoint, method, query, body, keys, sign, parse_envelope, .perform, .parser, is_async, page_size, max_pages, items_field, timeout, .get_timestamp_ms) {
  assert_scalar_character(base_url)
  assert_scalar_character(endpoint)
  assert_scalar_character(method)
  assert_list(query)
  if (!is.null(body)) {
    assert_list(body)
  }
  if (!is.null(keys)) {
    assert_list(keys)
  }
  if (!is.null(sign)) {
    assert_function(sign)
  }
  assert_function(parse_envelope)
  assert_function(.perform)
  assert_function(.parser)
  assert_scalar_logical(is_async)
  assert_scalar_count(page_size)
  assert_between(page_size, lower = 1)
  assert_scalar_double(max_pages)
  assert_between(max_pages, lower = 1)
  assert_scalar_character(items_field)
  assert_scalar_double(timeout)
  assert_between(timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  if (!is.null(.get_timestamp_ms)) {
    assert_function(.get_timestamp_ms)
  }
  return(invisible(NULL))
}

assert_return_kucoin_paginate <- function(value) {
  return(value)
}

assert_args_verify_symbol <- function(ticker) {
  assert_scalar_character(ticker)
  return(invisible(NULL))
}

assert_return_verify_symbol <- function(value) {
  assert_scalar_logical(value)
  return(value)
}

assert_args_validate_order_params <- function(type, symbol, side, clientOid, price, size, funds, stp, tags, remark, timeInForce, cancelAfter, postOnly, hidden, iceberg, visibleSize) {
  assert_scalar_character(type)
  assert_value_in_set(type, c("limit", "market"))
  assert_scalar_character(symbol)
  assert_scalar_character(side)
  assert_value_in_set(side, c("buy", "sell"))
  if (!is.null(clientOid)) {
    assert_scalar_character(clientOid)
  }
  if (!is.null(price)) {
    assert_any_of(
      price,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(size)) {
    assert_any_of(
      size,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(funds)) {
    assert_any_of(
      funds,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  if (!is.null(stp)) {
    assert_scalar_character(stp)
  }
  if (!is.null(tags)) {
    assert_scalar_character(tags)
  }
  if (!is.null(remark)) {
    assert_scalar_character(remark)
  }
  if (!is.null(timeInForce)) {
    assert_scalar_character(timeInForce)
  }
  if (!is.null(cancelAfter)) {
    assert_scalar_double(cancelAfter)
  }
  if (!is.null(postOnly)) {
    assert_scalar_logical(postOnly)
  }
  if (!is.null(hidden)) {
    assert_scalar_logical(hidden)
  }
  if (!is.null(iceberg)) {
    assert_scalar_logical(iceberg)
  }
  if (!is.null(visibleSize)) {
    assert_any_of(
      visibleSize,
      function(.x) {
        assert_scalar_double(.x)
      },
      function(.x) {
        assert_scalar_character(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_validate_order_params <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_validate_margin_order_params <- function(isIsolated, autoBorrow, autoRepay) {
  if (!is.null(isIsolated)) {
    assert_scalar_logical(isIsolated)
  }
  if (!is.null(autoBorrow)) {
    assert_scalar_logical(autoBorrow)
  }
  if (!is.null(autoRepay)) {
    assert_scalar_logical(autoRepay)
  }
  return(invisible(NULL))
}

assert_return_validate_margin_order_params <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_validate_batch_order <- function(order) {
  assert_list(order)
  return(invisible(NULL))
}

assert_return_validate_batch_order <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_get_base_url <- function(url) {
  if (!is.null(url)) {
    assert_scalar_character(url)
  }
  return(invisible(NULL))
}

assert_return_get_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_get_futures_base_url <- function(url) {
  if (!is.null(url)) {
    assert_scalar_character(url)
  }
  return(invisible(NULL))
}

assert_return_get_futures_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_get_api_keys <- function(api_key, api_secret, api_passphrase, key_version) {
  assert_scalar_character(api_key)
  assert_scalar_character(api_secret)
  assert_scalar_character(api_passphrase)
  assert_scalar_character(key_version)
  return(invisible(NULL))
}

assert_return_get_api_keys <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_get_sub_account <- function(sub_account_name, sub_account_password) {
  assert_scalar_character(sub_account_name)
  assert_scalar_character(sub_account_password)
  return(invisible(NULL))
}

assert_return_get_sub_account <- function(value) {
  assert_list(value)
  return(value)
}

assert_return_time_convert_from_kucoin <- function(value) {
  assert_class(value, "POSIXct")
  return(value)
}

assert_return_time_convert_to_kucoin <- function(value) {
  assert_any_of(
    value,
    function(.x) {
      assert_scalar_double(.x)
    },
    function(.x) {
      assert_scalar_integer(.x)
    }
  )
  return(value)
}

